### ISSUE TITLE
cloud secrets are not unified

### ISSUE THREAD

**Issue by deitch** [packet-labs/helm-charts#4]
See [this ccm issue](https://github.com/packethost/packet-ccm/issues/22).

So far, at least ccm and csi, possibly others, use slightly different variants on how the secrets are structured.

Some use the secrets directly (e.g. ccm):

```yml
apiVersion: v1
kind: Secret
metadata:
  name: packet-cloud-config
  namespace: kube-system
stringData:
  apiKey: "SECRET_KEY"
  projectID: "PROJECT_UUID"
```

These consume the secrets directly as environment variables, e.g.:

```yml
        env:
          - name: PACKET_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: packet-cloud-config
                key: apiKey
          - name: PACKET_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: packet-cloud-config
                key: projectID
```

Others (e.g. csi) have a single key with json in it:

```yml
apiVersion: v1
kind: Secret
metadata:
  name: packet-cloud-config
  namespace: kube-system
stringData:
  cloud-sa.json: |
    {
    "apiKey": "SECRET_KEY",
    "projectID": "PROJECT_UUID"
    }
```

These _mount_ the secret as a file in the container and consume it via a config file, e.g.:

```yml
          args:
            - "--config=/etc/cloud-sa/cloud-sa.json"
          volumeMounts:
            - name: cloud-sa-volume
              readOnly: true
              mountPath: "/etc/cloud-sa"
      volumes:
        - name: cloud-sa-volume
          secret:
            secretName: packet-cloud-config
```

There are pros and cons to each approach. Neither is mandated by the csi, ccm or other standards. We should just decide which approach we are going to take and move them all to it.

Pros to env vars over file:

* easy to read, consume, and most importantly understand
* clearly 12-factor
* lots of people understand it

Pros to file over env var:

* kubernetes can update the secret in the file if it changes
* app _can_ be taught to poll the file regularly (or use inotify or similar) and, if it changes, restart itself; with env vars, container must be restarted to apply changes

The file pros might or might not be relevant, depending on if we actually expect these apps to change keys, and that they self-restart.

Let's pick one and go for it.

The other issue: technically, the README is incorrect, since it applies to some but not all charts. Once we unify it, that issue will be resolved.
